spring.application.name=pedidos-service

# Base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:pedidosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always

# Consola web de H2 para consultas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Propiedad para promociones (Parte 2)
promo.black-friday.activa=true